imagePullSecrets:
  - name: dockerconfigjson-ghcr

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
  hosts:
    - host: matrix-barcamp-widget.dev.nordeck.systems
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: matrix-barcamp-widget-tls
      hosts:
        - matrix-barcamp-widget.dev.nordeck.systems
